image: "python:3.8-slim"

before_script:
  - python3 --version

stages:
  - analysis
  - test
  - deploy

test:
 stage: test
 script:
   - python3 -m venv civenv/
   - source civenv/bin/activate
   - pip install --upgrade pip
   - pip install -r requirements.txt
   - python manage.py makemigrations
   - python manage.py migrate
   - python manage.py test

pep8:
  stage: analysis
  script:
    - pip freeze

Docker Build:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - export DOCKER_TAG=latest
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "registry.gitlab.com/zackcmariano/django-devops:$DOCKER_TAG"
  
  script:
    - docker build -t "registry.gitlab.com/zackcmariano/django-devops:$DOCKER_TAG" .
    - docker push "registry.gitlab.com/zackcmariano/django-devops:$DOCKER_TAG"


  #script:
    #- TAG="$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME"
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    #- docker build -f Dockerfile -t $TAG .
    #- docker push $TAG
