image: "python:3.8-slim"

before_script:
  - python3 --version

stages:
  - activate
  - test
  - deploy

activate:
 stage: activate
 script:
   - python3 -m venv civenv/
   - source civenv/bin/activate
   - pip install --upgrade pip
   - pip install -r requirements.txt
   - alias manage='python $VIRTUAL_ENV/../manage.py'
   - manage makemigrations
   - manage migrate
  #- python manage.py test

test:
  stage: test
  script:
    - manage test

Docker Build:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - export DOCKER_TAG=developer
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "registry.gitlab.com/zackcmariano/django-devops:$DOCKER_TAG"
  
  script:
    - docker build -t "registry.gitlab.com/zackcmariano/django-devops:$DOCKER_TAG" .
    - docker push "registry.gitlab.com/zackcmariano/django-devops:$DOCKER_TAG"
  
  only:
    - main
