image: "python:3.8-slim"

before_script:
  - python3 --version

stages:
  - analysis
  - test

test:
 stage: test
 script:
   - python3 -m venv civenv/
   - source civenv/bin/activate
   - pip install requirements.txt
   - python manage.py makemigrations
   - python manage.py migrate
   - python manage.py test

pep8:
  stage: analysis
  script:
    - pycodestyle manage.py