image: "python:3.8-slim"

before_script:
  - python3 --version

stages:
  - analysis
  - test
  - deploy

test:
 stage: test
 script:
   - python3 -m venv civenv/
   - source civenv/bin/activate
   - pip install --upgrade pip
   - pip install -r requirements.txt
   - python manage.py makemigrations
   - python manage.py migrate
   - python manage.py test

pep8:
  stage: analysis
  script:
    - pip freeze

build_standard_docker:
  image: docker:19.03
  stage: deploy
  services:
    - docker:19.03.0
  variables:
    DOCKER_HOST: tcp://docker:2377/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  only:
    - master
    - main
  script:
    - TAG="$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile -t $TAG .
    - docker push $TAG
