---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: zackcmariano/django-devops:{{tag}}
---
apiVersion: v1
kind: Service
metadata:
  name: django-service 
spec:
  selector:
    app: django-app
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 8000
  type: LoadBalancer